### ISSUE TITLE
consolidate `MarketPlace.exchangeRate` method

### ISSUE THREAD

**Issue by alexanderwende** [Swivel-Finance/swivel-js#96]
The `MarketPlace.sol` contract has an `exchangeRate` method, so does the swivel-js HOC, both do slightly different things wrt retrieving the exchange rate for Compound and Rari. 

We need to figure out how to name these methods on the HOC to have them co-exist and to document their differences and decide if we want 2 different `exchangeRate` methods at all.

Currently the `MarketPlace.sol` contract's `exchangeRate` uses `libCompound`/`libFuse` for calculating Compound's/Rari's exchange rate, while the HOC uses the cToken's `exchangeRateCurrent` (the HOC can't access/invoke solidity libraries).

@robrobbins @JTraversa ideas/comments/suggestions are welcome.

**Comment by robrobbins** [comment]
@JTraversa implemented libCompound / libFuse in Swiv3 due to the large gas savings over the previously used exchangeRateCurrent. I'll leave any deeper discussion of that switch to him

WRT having both;

Why? Two sources of truth is never good. Is there some purpose for keeping exchangeRateCurrent around in the FE? The Protocol should be the source of truth. FE should likely do the same thing no? Can't FE just call the exposed MarketPlace.exchangeRate method? I'm likely missing something here so lemme know.

**Comment by JTraversa** [comment]
I think the swivel-js HOC should just read `exchangeRate` through the method provided on marketplace.sol to ensure everything is aligned across various cTokens + it might reduce complexity just a bit on FE as we add more tokens?

**Comment by JTraversa** [comment]
On LibCompound / LibFuse, still some math investigation left. There is a chance that we revert to compound's exchangeRateCurrent in the lib if we literally cannot find the cause of math differences, but regardless reading from marketplace.sol reduces the frontend's need to read all the different compounding token abi's
